import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToasterContext from "./context/ToasterContext";
import AuthContext from "./context/AuthContext";
import ActiveStatus from "./components/ActiveStatus";
import { ThemeProvider } from "@/app/components/theme-provider"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Messenger Clone",
  description: "Generated by create next app",
  icons: {
      icon: '../../public/images/messengelogo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className} dark:bg-gray-900`} suppressHydrationWarning={true}>
            <ThemeProvider attribute="class" defaultTheme="light" >

            <AuthContext>
                  <ToasterContext />
                  <ActiveStatus />
                  {children}
            </AuthContext>
            </ThemeProvider>
      </body>
    </html>
  );
}
